spring:
  application:
    name: incode-home-task
  cache:
    cache-names: verificationById
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=30m
  profiles:
    default: local

third-party:
  base-url: http://localhost:8080

logging:
  file:
    name: logs/incode-home-task.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [traceId=%X{traceId:-}, spanId=%X{spanId:-}, verificationId=%X{verificationId:-}, query=%X{query:-}] %logger{36} - %msg%n%ex"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [traceId=%X{traceId:-}, spanId=%X{spanId:-}, verificationId=%X{verificationId:-}, query=%X{query:-}] %logger{36} - %msg%n%ex"

management:
  observations:
    annotations:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,logfile,loggers
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  circuitbreaker:
    instances:
      freeThirdParty:
        failureRateThreshold: 90
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 100s
      premiumThirdParty:
        failureRateThreshold: 50
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
