spring:
  application:
    name: incode-home-task
  profiles:
    default: local

third-party:
  base-url: http://localhost:8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [verificationId=%X{verificationId:-}, query=%X{query:-}] %logger{36} - %msg%n%ex"

resilience4j:
  circuitbreaker:
    instances:
      freeThirdParty:
        failureRateThreshold: 90
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 100s
      premiumThirdParty:
        failureRateThreshold: 50
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
