spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/incode_home_task}
    username: ${DATABASE_USERNAME:hometask}
    password: ${DATABASE_PASSWORD:mypass321}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  tracing:
    export:
      otlp:
        enabled: ${OTLP_TRACING_ENABLED:false}
  otlp:
    metrics:
      export:
        enabled: ${OTLP_METRICS_ENABLED:false}
